export const UScities = {
  'New York': 'NYC',
  Atlanta: 'ATL',
  'Los Angeles': 'LAX',
  Chicago: 'CHI',
  'Fort Worth': 'DFW',
  Denver: 'DEN',
  'San Francisco': 'SFO',
  'Las Vegas': 'LAS',
  Seattle: 'SEA',
  Charlotte: 'CLT',
  Orlando: 'ORL',
  Phoenix: 'PHX',
  Miami: 'MIA',
  Houston: 'HOU',
  Boston: 'BOS',
  Minneapolis: 'MSP',
  Detroit: 'DTW',
  'Fort Lauderdale': 'FLL',
  Philadelphia: 'PHL',
  Baltimore: 'BWI',
  'Salt Lake City': 'SLC',
  'Washington D.C': 'WAS',
  'San Diego': 'SAN',
  Tampa: 'TPA',
  Honolulu: 'HNL',
  Portland: 'POR'
};

export const majCities = Object.keys(UScities);
