export const USstates = [
  'New York',
  'Atlanta',
  'Los Angeles',
  'Chicago',
  'Fort Worth',
  'Denver',
  'San Francisco',
  'Las Vegas',
  'Seattle',
  'Charlotte',
  'Orlando',
  'Phoenix',
  'Miami',
  'Houston',
  'Boston',
  'Minneapolis',
  'Detroit',
  'Fort Lauderdale',
  'Philadelphia',
  'Baltimore',
  'Salt Lake City',
  'Washington D.C',
  'San Diego',
  'Tampa',
  'Honolulu',
  'Portland'
];
